services:
  - type: web
    name: summarizer-website
    runtime: static
    rootDir: ./website
    buildCommand: yarn build
    staticPublishPath: ./dist
    domains:
      - summarizer.aldr.io
    routes:
      - type: rewrite
        source: /*
        destination: /
    envVars:
      - key: VITE_API_URL
        value: https://www.example.com

  - type: web
    name: summarizer-api
    runtime: python
    rootDir: ./api
    region: ohio
    buildCommand: python ./build.py
    startCommand: gunicorn --bind 0.0.0.0:8000 wsgi
    healthCheckPath: /healthz
    envVars:
      - key: PRODUCTION
        value: "True"
      - key: WEBAPP_URL
        value: https://summarizer.aldr.io
